//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioClima.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClimaPorPaisCiudad
    {
        public int IdClima { get; set; }
        public Nullable<int> IdPais { get; set; }
        public string IdCiudad { get; set; }
        public string Dia { get; set; }
        public string Temperatura_grados_c { get; set; }
        public string Temperatura_grados_f { get; set; }
        public string Prob_precip { get; set; }
        public string Humedad { get; set; }
        public string Viento { get; set; }
        public string Icono { get; set; }
    }
}
